services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /opt/nginx-proxy-manager/data:/data
      - /opt/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      # für Auslieferung von hochgeladenen Bildern 
      - /root/bierfestival_uploads:/var/www/bierfestival/uploads  # Der Pfad /var/www/bierfestival/uploads ist der Pfad *innerhalb* des Nginx-Proxy-Manager-Containers -> entspricht alias forwarding in nginx config
      - /root/srv/maps/data:/var/www/bierfestival/maps
      # Pfad muss entsprechend zum Server passend angepasst werden, damit die hochgeladenen Bilder und Mapdaten auch vom Nginx-Proxy-Manager-Container aus erreichbar sind.
    networks:
      - nginx-proxy-manager
networks:
  nginx-proxy-manager:
    external: true

volumes:
  npm_data: {} # Leeres Mapping bedeutet: Docker erstellt dieses Volume mit Standardeinstellungen
  npm_letsencrypt: {} # Ebenso